name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  CI:
    runs-on: ubuntu-latest
    steps :
           - name: Call Azure Pipeline thru CURL
             run : |
                   curl --user '':--header "Content-Type:application/json" --header "Accept:application/json" https://dev.azure.com/tr-ihn-sandbox/JiraAdoMigrate/_build?definitionId=28
